services:
  db:
    image: postgres:16
    container_name: mlecture_backend_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - mlecture_network
  mlecture_backend:
    build: .
    container_name: mlecture_backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - mlecture_network
volumes:
  postgres_data:
networks:
  mlecture_network:
    driver: bridge